#import <React/RCTViewManager.h>

@interface RCT_EXTERN_MODULE(PaywallScreenViewManager, RCTViewManager)
RCT_EXPORT_VIEW_PROPERTY(placementIdentifier, NSString)
RCT_EXPORT_VIEW_PROPERTY(onStartLoading, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onReceiveView, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onLoadingError, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTransactionStarted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onFinished, RCTBubblingEventBlock)

@end
